title: QuestI0
description: QuestI0 é um portal para o aprendizado de Lógica Digital
encoding: UTF-8

show_downloads: false
google_analytics:

theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
